services:
  # Service Base de Données
  db:
    image: postgres:15-alpine
    container_name: projet-db
    # On charge les variables depuis le fichier .env
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      # On utilise les variables $VAR ici aussi pour être cohérent
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Service API
  api:
    build: ./backend
    container_name: projet-api
    depends_on:
      db:
        condition: service_healthy
    # Ici, on mappe les variables du .env vers les variables attendues par Node
    environment:
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${POSTGRES_USER} # On réutilise la variable définie pour Postgres
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/status"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Service Frontend
  front:
    build: ./frontend
    container_name: projet-front
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
